---
apiVersion: v1
kind: Secret
metadata:
  name: studio-secret
  labels:
    lechaterrant.com/app: studio
    lechaterrant.com/stack: backend
stringData:
  # postgresql://user:password@host:port/dbname
  DATABASE_URL: postgresql://root:dbpass@postgres-service:5432/app
