apiVersion: v1
kind: Secret
metadata:
  name: registry-key
stringData:
  # To add your own token, create a new Personal Access Token with read:packages on github
  # Then, base64 encode as follows : echo -n <your-github-username>:<TOKEN> | base64
  # Replace <AUTH> by the base64 result
  .dockerconfigjson: '{"auths":{"docker.pkg.github.com":{"auth":"<AUTH>"}}}'
type: kubernetes.io/dockerconfigjson
