---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: products
  namespace: argocd
spec:
  description: Product related apps
  sourceRepos:
    - https://github.com/LeChatErrant/ops-template
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
