---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-statefulset
  namespace: monitoring
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch-headless-service
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      serviceAccountName: elasticsearch-logging
      containers:
        - image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
          name: elasticsearch
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
            - name: elasticsearch-tls
              mountPath: /usr/share/elasticsearch/config/certs
          env:
            - name: CLUSTER_NAME
              value: elasticsearch
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
        - name: elasticsearch-vm-max-map-init
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: elasticsearch-increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
        - name: elasticsearch-set-permissions
          image: busybox
          command: [ "sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data" ]
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
      volumes:
        - name: elasticsearch-config
          configMap:
            name: elasticsearch-configmap
        - name: elasticsearch-tls
          secret:
            # elasticsearch-tls secret will be added once certificates has been generated
            # those certificates need elasticsearch to be running to be generated
            # So, we have to
            #  - Run elasticsearch without tls
            #  - Generate tls certificates (see details in deploy.sh script
            #  - Inject certificates as a secret in the K8S cluster
            #  - Change elasticsearch configuration
            #  - Restart elasticsearch with the new configuration
            optional: true
            secretName: elasticsearch-tls
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi