---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless-service
  namespace: monitoring
  labels:
    app: elasticsearch
spec:
  # Create a headless service, providing hostname for each of statefulset pods
  # (elasticsearch-headless-service-0, etc)
  clusterIP: None
  # Create endpoints also if the related pod isn't ready
  publishNotReadyAddresses: true
  ports:
    - port: 9200
      protocol: TCP
      name: http
    - port: 9300
      protocol: TCP
      name: transport
  selector:
    app: elasticsearch