---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml
resources:
  - letsencrypt.issuer.yaml
  - tls.certificate.yaml