---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    lechaterrant.com/app: redis
    lechaterrant.com/stack: backend
spec:
  type: ClusterIP
  selector:
    lechaterrant.com/app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
