---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: heartbeat
  labels:
    app: heartbeat
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - pods
    verbs:
     - get
     - list
     - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: monitoring
  name: heartbeat
subjects:
  - kind: ServiceAccount
    name: heartbeat
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: heartbeat
  apiGroup: rbac.authorization.k8s.io

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: heartbeat
  namespace: monitoring
  labels:
    app: heartbeat
