---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: default
  labels:
    lechaterrant.com/app: traefik
    lechaterrant.com/stack: traefik
spec:
  redirectScheme:
    scheme: https
    permanent: true