---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  labels:
    lechaterrant.com/app: api
    lechaterrant.com/stack: backend
stringData:
  # postgresql://user:password@host:port/dbname
  DATABASE_URL: postgresql://root:dbpass@postgres-service:5432/app
  REDIS_PASS: redispass
  SESSION_SECRET: keyboard_cat
  DEFAULT_ADMIN_EMAIL: admin@api-template.com
  DEFAULT_ADMIN_PASSWORD: admin