apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
stringData:
  # Put your TLS certificate here
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    XXX
    -----END CERTIFICATE-----
  # Put your TLS private key here
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    YYY
    -----END RSA PRIVATE KEY-----
type: kubernetes.io/tls