---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    lechaterrant.com/app: postgres
    lechaterrant.com/stack: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# If you are in a cloud provider, it's likely that the PersistentVolume will be created automatically
# If not, you can describe PersistentVolume specs below

---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: postgres-pv
#   labels:
#     lechaterrant.com/app: postgres
#     lechaterrant.com/stack: backend
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /mnt/data
#     type: DirectoryOrCreate