---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
stringData:
  # Default password for admin
  # !!! Need to be BCRYPT encrypted !!!
  # Here, the clear password is 'admin', so you can log in using admin:admin
  admin.password: $2a$12$gV6WUTviCkCt1PmxWKjeme893hZ5EFAOvenpMCwwo4kSuBvcHqrAS
  webhook.github.secret: github webhook secret
