---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: ''
  policy.csv: |
    p, role:dev, applications, get, app/*, allow

    g, maintainer, role:admin
    g, maintainer, role:dev

    g, dev, role:dev

    g, external, role:readonly
